# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('userName', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
